# Generated by Django 3.2.9 on 2021-11-18 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('release_date', models.PositiveIntegerField(default=None)),
                ('cost', models.FloatField(default=None)),
                ('image', models.CharField(default=None, max_length=200)),
                ('colour', models.ManyToManyField(related_name='sneakers', to='colours.Colour')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
