# Generated by Django 3.2.8 on 2021-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colours', '0001_initial'),
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='colour',
            field=models.ManyToManyField(related_name='colours', to='colours.Colour'),
        ),
    ]
