# Generated by Django 3.2.8 on 2021-10-22 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colours', '0001_initial'),
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='jwt_auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='colour',
            field=models.ManyToManyField(related_name='sneakers', to='colours.Colour'),
        ),
    ]
