# Generated by Django 3.2.8 on 2021-10-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sneakers.sneaker')),
            ],
        ),
    ]
